//  Vendeur actions
export const GET_ARTICLES = "GET_ARTICLES";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const REMOVE_ARTICLE ="REMOVE_ARTICLE";
export const MODIFY_ARTICLE = "MODIFY_ARTICLE";
export const CREATE_FACTURE = "CREATE_FACTURE";
export const GET_SOLDEVENDEUR = "GET_SOLDEVENDEUR";
export const ADD_TOSOLDEVENDEUR = "ADD_TOSOLDEVENDEUR";

//  Client actions
export const GET_PANIER = "GET_PANIER";
export const ADD_TOPANIER = "ADD_TOPANIER";
export const DELETE_FROMPANIER = "DELETE_FROMPANIER";
export const EMPTY_PANIER = "EMPTY_PANIER";
export const ARCHIVE_PANIER = "ARCHIVE_PANIER";
export const GET_ARCHIVEPANIER = "GET_ARCHIVEPANIER";
export const GET_SOLDE = "GET_SOLDE";
export const ADD_TOSOLDE = "ADD_TOSOLDE";
export const SUBTRACT_FROMSOLDE = "SUBTRACT_FROMSOLDE";